x-api: &api
  image: zanfranceschi/rinha-de-backend-2026-zan-clojure:ann-ivf-202604212022
  environment:
    NPROBE: 4
    PORT: "3000"
    JAVA_TOOL_OPTIONS: >-
      -Xmx100m
      -Xms100m
      -XX:MaxMetaspaceSize=60m
      -Xss256k
      -XX:+UseSerialGC
      -XX:+DisableExplicitGC
  deploy:
    resources:
      limits:
        cpus: "0.45"
        memory: "170M"

services:
  api1:
    <<: *api

  api2:
    <<: *api

  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10M"
