x-api: &api
  image: zanfranceschi/rinha-de-backend-2026-clojure-exemplo:202604190029
  environment:
    PORT: "3000"
    JAVA_TOOL_OPTIONS: >-
      -Xmx96m
      -Xms96m
      -XX:MaxMetaspaceSize=96m
      -XX:+UseSerialGC
      -Xss256k
      -XX:TieredStopAtLevel=1
  deploy:
    resources:
      limits:
        cpus: "0.4"
        memory: "160M"

services:
  api1:
    <<: *api

  api2:
    <<: *api

  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30M"
