services:
  api1:
    build: .
    environment:
      PORT: "3000"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "350M"

  api2:
    build: .
    environment:
      PORT: "3000"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "350M"

  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "128M"
