@port = 9999

### Health check
GET http://localhost:{{port}}/ready

### Legit transaction - low amount, known merchant, close to home
POST http://localhost:{{port}}/fraud-score
Content-Type: application/json

{
  "id": "tx-1329056812",
  "transaction": { "amount": 41.12, "installments": 2, "requested_at": "2026-03-11T18:45:53Z" },
  "customer": { "avg_amount": 82.24, "tx_count_24h": 3, "known_merchants": ["MERC-003", "MERC-016"] },
  "merchant": { "id": "MERC-016", "mcc": "5411", "avg_amount": 60.25 },
  "terminal": { "is_online": false, "card_present": true, "km_from_home": 29.23 },
  "last_transaction": null
}

### Fraudulent transaction - high amount, far from home, unknown merchant
POST http://localhost:{{port}}/fraud-score
Content-Type: application/json

{
  "id": "tx-3330991687",
  "transaction": { "amount": 9505.97, "installments": 10, "requested_at": "2026-03-14T05:15:12Z" },
  "customer": { "avg_amount": 81.28, "tx_count_24h": 20, "known_merchants": ["MERC-008", "MERC-007", "MERC-005"] },
  "merchant": { "id": "MERC-068", "mcc": "7802", "avg_amount": 54.86 },
  "terminal": { "is_online": false, "card_present": true, "km_from_home": 952.27 },
  "last_transaction": null
}
