x-api: &api
  image: rinha-de-backend-2026-clojure-exemplo:latest
  environment:
    PORT: "3000"
    JAVA_TOOL_OPTIONS: >-
      -Xmx80m
      -Xms80m
      -XX:MaxMetaspaceSize=50m
      -XX:+UseSerialGC
      -Xss256k
  deploy:
    resources:
      limits:
        cpus: "0.4"
        memory: "165M"

services:
  api1:
    <<: *api

  api2:
    <<: *api

  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20M"