FROM clojure:temurin-25-tools-deps AS build
WORKDIR /app
COPY deps.edn build.clj ./
RUN clojure -P && clojure -P -T:build
COPY src src
COPY resources resources
RUN mkdir -p classes && clojure -T:build uber

FROM ghcr.io/graalvm/native-image-community:25 AS native
WORKDIR /app
COPY --from=build /app/target/fraud.jar /app/fraud.jar
RUN native-image \
    --no-fallback \
    -H:+ReportExceptionStackTraces \
    -H:+AllowDeprecatedInitializeAllClassesAtBuildTime \
    --initialize-at-build-time \
    -jar fraud.jar \
    fraud

FROM alpine:3
WORKDIR /app
RUN apk add --no-cache libstdc++ gcompat
COPY --from=native /app/fraud /app/fraud
ENTRYPOINT ["/app/fraud"]
